Repository exasol/bucketfs-python, pull requests merged in 2024-07, with the labels that each got.

#149 #149 Added documentation for SaaS and the PathLike
  doc/api.rst
  doc/changes/unreleased.md
  doc/examples/bucket_saas.py
  doc/examples/delete.py
  doc/examples/download.py
  doc/examples/list.py
  doc/examples/path_like.py
  doc/examples/quickstart.py
  doc/examples/service.py
  doc/examples/upload.py
  doc/user_guide/basics.rst
  doc/user_guide/user_guide.rst
  exasol/bucketfs/_buckets.py
  exasol/bucketfs/_path.py
Labels: documentation

#148 Update dependencies
  doc/changes/unreleased.md
  poetry.lock
  pyproject.toml
Labels: security

#154 Refactor GitHub workflows and prepare release 0.12.0
  .github/workflows/build-and-publish.yml
  .github/workflows/checks.yml
  .github/workflows/ci.yml
  .github/workflows/pr-merge.yml
  doc/changes/changelog.md
  doc/changes/changes_0.12.0.md
  doc/changes/unreleased.md
  exasol/bucketfs/version.py
  pyproject.toml
Labels: refactoring
